/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SSectionFourthItems, } from "./components/cnt-flexy-view-viskhan-sbank-about-1_01/res/view/cnt-flexy-view-viskhan-sbank-about/interface/common.interface";
import { SCollaborationItems, } from "./components/cnt-flexy-view-viskhan-sbank-collaboration-1_01/res/view/cnt-flexy-view-viskhan-sbank-collaboration/interface/common.interface";
import { SSectionSecondItems, } from "./components/cnt-flexy-view-viskhan-sbank-dowork-1_01/res/view/cnt-flexy-view-viskhan-sbank-dowork/interface/common.interface";
import { SSectionFirstItems, } from "./components/cnt-flexy-view-viskhan-sbank-estimates-1_01/res/view/cnt-flexy-view-viskhan-sbank-estimates/interface/common.interface";
import { SFooterItems, } from "./components/cnt-flexy-view-viskhan-sbank-footer-1_01/res/view/cnt-flexy-view-viskhan-sbank-footer/interface/common.interface";
import { SHeaderItems, } from "./components/cnt-flexy-view-viskhan-sbank-header-1_01/res/view/cnt-flexy-view-viskhan-sbank-header/interface/common.interface";
import { SReviewItems, } from "./components/cnt-flexy-view-viskhan-sbank-review-1_01/res/view/cnt-flexy-view-viskhan-sbank-review/interface/common.interface";
import { SStaffingItems, } from "./components/cnt-flexy-view-viskhan-sbank-staffing-1_01/res/view/cnt-flexy-view-viskhan-sbank-staffing/interface/common.interface";
import { SSectionThirdItems, } from "./components/cnt-flexy-view-viskhan-sbank-structure-1_01/res/view/cnt-flexy-view-viskhan-sbank-structure/interface/common.interface";
import { SSummaryItems, } from "./components/cnt-flexy-view-viskhan-sbank-summary-1_01/res/view/cnt-flexy-view-viskhan-sbank-summary/interface/common.interface";
import { STimelineItems, } from "./components/cnt-flexy-view-viskhan-sbank-timeline-1_01/res/view/cnt-flexy-view-viskhan-sbank-timeline/interface/common.interface";
import { SWindowItems, } from "./components/cnt-flexy-view-viskhan-window-1_01/interface/common.interface";
export namespace Components {
    interface CntFlexyViewViskhanSbankAbout {
        /**
          * Данные компонента Collaboration
         */
        "payload": any;
        /**
          * Интерфейс для SectionFourth
         */
        "sectionFourth": SSectionFourthItems[];
    }
    interface CntFlexyViewViskhanSbankAbout1_01 {
        "pathToAssets": string;
        /**
          * Данные компонента About
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankCollaboration {
        /**
          * Данные компонента collaboration
         */
        "payload": any;
        /**
          * Интерфейс для Collaboration
         */
        "sectionThird": SCollaborationItems[];
    }
    interface CntFlexyViewViskhanSbankCollaboration1_01 {
        "pathToAssets": string;
        /**
          * Данные компонента Collaboration
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankDowork {
        "pathToAssets": string;
        /**
          * Массив для Dowork
         */
        "payload": any;
        /**
          * Интерфейс для Dowork
         */
        "sectionSecond": SSectionSecondItems[];
    }
    interface CntFlexyViewViskhanSbankDowork1_01 {
        "pathToAssets": string;
        /**
          * Данные компонента collaboration
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankEstimates {
        /**
          * Массив для Estimates
         */
        "payload": any;
        /**
          * Интерфейс для Estimates
         */
        "sectionFirst": SSectionFirstItems[];
    }
    interface CntFlexyViewViskhanSbankEstimates1_01 {
        "pathToAssets": string;
        /**
          * Данные компонента estimates
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankFooter {
        /**
          * Массив для Footer
         */
        "categories": any;
        /**
          * Интерфейс для Footer
         */
        "footer": SFooterItems[];
    }
    interface CntFlexyViewViskhanSbankFooter1_01 {
        /**
          * Данные компонента footer
         */
        "categories": any;
        "pathToAssets": string;
    }
    interface CntFlexyViewViskhanSbankHeader {
        /**
          * Массив для Header
         */
        "categories": any;
        /**
          * Интерфейс для Header
         */
        "header": SHeaderItems[];
    }
    interface CntFlexyViewViskhanSbankHeader1_01 {
        /**
          * Данные компонента header
         */
        "categories": any;
        "pathToAssets": string;
    }
    interface CntFlexyViewViskhanSbankReview {
        /**
          * Интерфейс для SReviewItems
         */
        "Review": SReviewItems[];
        /**
          * Данные компонента Review
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankReview1_01 {
        "pathToAssets": string;
        /**
          * Данные компонента Review
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankStaffing {
        /**
          * Интерфейс для Staffing
         */
        "Staffing": SStaffingItems[];
        /**
          * Данные компонента Staffing
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankStaffing1_01 {
        "pathToAssets": string;
        /**
          * Данные компонента Staffing
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankStructure {
        /**
          * Массив для Structure
         */
        "payload": any;
        /**
          * Интерфейс для Structure
         */
        "sectionThird": SSectionThirdItems[];
    }
    interface CntFlexyViewViskhanSbankStructure1_01 {
        "pathToAssets": string;
        /**
          * Данные компонента collaboration
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankSummary {
        /**
          * Интерфейс для Summary
         */
        "Summary": SSummaryItems[];
        /**
          * Данные компонента Summary
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankSummary1_01 {
        "pathToAssets": string;
        /**
          * Данные компонента Summary
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankTimeline {
        /**
          * Интерфейс для Timeline
         */
        "Timeline": STimelineItems[];
        /**
          * Данные компонента Timeline
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanSbankTimeline1_01 {
        "pathToAssets": string;
        /**
          * Данные компонента Timeline
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanWindow1_01 {
        /**
          * Интерфейс для Window
         */
        "Window": SWindowItems[];
        "pathToAssets": string;
        /**
          * Данные для Window
         */
        "payload": any;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCntFlexyViewViskhanSbankAboutElement extends Components.CntFlexyViewViskhanSbankAbout, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankAboutElement: {
        prototype: HTMLCntFlexyViewViskhanSbankAboutElement;
        new (): HTMLCntFlexyViewViskhanSbankAboutElement;
    };
    interface HTMLCntFlexyViewViskhanSbankAbout1_01Element extends Components.CntFlexyViewViskhanSbankAbout1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankAbout1_01Element: {
        prototype: HTMLCntFlexyViewViskhanSbankAbout1_01Element;
        new (): HTMLCntFlexyViewViskhanSbankAbout1_01Element;
    };
    interface HTMLCntFlexyViewViskhanSbankCollaborationElement extends Components.CntFlexyViewViskhanSbankCollaboration, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankCollaborationElement: {
        prototype: HTMLCntFlexyViewViskhanSbankCollaborationElement;
        new (): HTMLCntFlexyViewViskhanSbankCollaborationElement;
    };
    interface HTMLCntFlexyViewViskhanSbankCollaboration1_01Element extends Components.CntFlexyViewViskhanSbankCollaboration1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankCollaboration1_01Element: {
        prototype: HTMLCntFlexyViewViskhanSbankCollaboration1_01Element;
        new (): HTMLCntFlexyViewViskhanSbankCollaboration1_01Element;
    };
    interface HTMLCntFlexyViewViskhanSbankDoworkElement extends Components.CntFlexyViewViskhanSbankDowork, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankDoworkElement: {
        prototype: HTMLCntFlexyViewViskhanSbankDoworkElement;
        new (): HTMLCntFlexyViewViskhanSbankDoworkElement;
    };
    interface HTMLCntFlexyViewViskhanSbankDowork1_01Element extends Components.CntFlexyViewViskhanSbankDowork1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankDowork1_01Element: {
        prototype: HTMLCntFlexyViewViskhanSbankDowork1_01Element;
        new (): HTMLCntFlexyViewViskhanSbankDowork1_01Element;
    };
    interface HTMLCntFlexyViewViskhanSbankEstimatesElement extends Components.CntFlexyViewViskhanSbankEstimates, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankEstimatesElement: {
        prototype: HTMLCntFlexyViewViskhanSbankEstimatesElement;
        new (): HTMLCntFlexyViewViskhanSbankEstimatesElement;
    };
    interface HTMLCntFlexyViewViskhanSbankEstimates1_01Element extends Components.CntFlexyViewViskhanSbankEstimates1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankEstimates1_01Element: {
        prototype: HTMLCntFlexyViewViskhanSbankEstimates1_01Element;
        new (): HTMLCntFlexyViewViskhanSbankEstimates1_01Element;
    };
    interface HTMLCntFlexyViewViskhanSbankFooterElement extends Components.CntFlexyViewViskhanSbankFooter, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankFooterElement: {
        prototype: HTMLCntFlexyViewViskhanSbankFooterElement;
        new (): HTMLCntFlexyViewViskhanSbankFooterElement;
    };
    interface HTMLCntFlexyViewViskhanSbankFooter1_01Element extends Components.CntFlexyViewViskhanSbankFooter1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankFooter1_01Element: {
        prototype: HTMLCntFlexyViewViskhanSbankFooter1_01Element;
        new (): HTMLCntFlexyViewViskhanSbankFooter1_01Element;
    };
    interface HTMLCntFlexyViewViskhanSbankHeaderElement extends Components.CntFlexyViewViskhanSbankHeader, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankHeaderElement: {
        prototype: HTMLCntFlexyViewViskhanSbankHeaderElement;
        new (): HTMLCntFlexyViewViskhanSbankHeaderElement;
    };
    interface HTMLCntFlexyViewViskhanSbankHeader1_01Element extends Components.CntFlexyViewViskhanSbankHeader1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankHeader1_01Element: {
        prototype: HTMLCntFlexyViewViskhanSbankHeader1_01Element;
        new (): HTMLCntFlexyViewViskhanSbankHeader1_01Element;
    };
    interface HTMLCntFlexyViewViskhanSbankReviewElement extends Components.CntFlexyViewViskhanSbankReview, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankReviewElement: {
        prototype: HTMLCntFlexyViewViskhanSbankReviewElement;
        new (): HTMLCntFlexyViewViskhanSbankReviewElement;
    };
    interface HTMLCntFlexyViewViskhanSbankReview1_01Element extends Components.CntFlexyViewViskhanSbankReview1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankReview1_01Element: {
        prototype: HTMLCntFlexyViewViskhanSbankReview1_01Element;
        new (): HTMLCntFlexyViewViskhanSbankReview1_01Element;
    };
    interface HTMLCntFlexyViewViskhanSbankStaffingElement extends Components.CntFlexyViewViskhanSbankStaffing, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankStaffingElement: {
        prototype: HTMLCntFlexyViewViskhanSbankStaffingElement;
        new (): HTMLCntFlexyViewViskhanSbankStaffingElement;
    };
    interface HTMLCntFlexyViewViskhanSbankStaffing1_01Element extends Components.CntFlexyViewViskhanSbankStaffing1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankStaffing1_01Element: {
        prototype: HTMLCntFlexyViewViskhanSbankStaffing1_01Element;
        new (): HTMLCntFlexyViewViskhanSbankStaffing1_01Element;
    };
    interface HTMLCntFlexyViewViskhanSbankStructureElement extends Components.CntFlexyViewViskhanSbankStructure, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankStructureElement: {
        prototype: HTMLCntFlexyViewViskhanSbankStructureElement;
        new (): HTMLCntFlexyViewViskhanSbankStructureElement;
    };
    interface HTMLCntFlexyViewViskhanSbankStructure1_01Element extends Components.CntFlexyViewViskhanSbankStructure1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankStructure1_01Element: {
        prototype: HTMLCntFlexyViewViskhanSbankStructure1_01Element;
        new (): HTMLCntFlexyViewViskhanSbankStructure1_01Element;
    };
    interface HTMLCntFlexyViewViskhanSbankSummaryElement extends Components.CntFlexyViewViskhanSbankSummary, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankSummaryElement: {
        prototype: HTMLCntFlexyViewViskhanSbankSummaryElement;
        new (): HTMLCntFlexyViewViskhanSbankSummaryElement;
    };
    interface HTMLCntFlexyViewViskhanSbankSummary1_01Element extends Components.CntFlexyViewViskhanSbankSummary1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankSummary1_01Element: {
        prototype: HTMLCntFlexyViewViskhanSbankSummary1_01Element;
        new (): HTMLCntFlexyViewViskhanSbankSummary1_01Element;
    };
    interface HTMLCntFlexyViewViskhanSbankTimelineElement extends Components.CntFlexyViewViskhanSbankTimeline, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankTimelineElement: {
        prototype: HTMLCntFlexyViewViskhanSbankTimelineElement;
        new (): HTMLCntFlexyViewViskhanSbankTimelineElement;
    };
    interface HTMLCntFlexyViewViskhanSbankTimeline1_01Element extends Components.CntFlexyViewViskhanSbankTimeline1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanSbankTimeline1_01Element: {
        prototype: HTMLCntFlexyViewViskhanSbankTimeline1_01Element;
        new (): HTMLCntFlexyViewViskhanSbankTimeline1_01Element;
    };
    interface HTMLCntFlexyViewViskhanWindow1_01Element extends Components.CntFlexyViewViskhanWindow1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanWindow1_01Element: {
        prototype: HTMLCntFlexyViewViskhanWindow1_01Element;
        new (): HTMLCntFlexyViewViskhanWindow1_01Element;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cnt-flexy-view-viskhan-sbank-about": HTMLCntFlexyViewViskhanSbankAboutElement;
        "cnt-flexy-view-viskhan-sbank-about-1_01": HTMLCntFlexyViewViskhanSbankAbout1_01Element;
        "cnt-flexy-view-viskhan-sbank-collaboration": HTMLCntFlexyViewViskhanSbankCollaborationElement;
        "cnt-flexy-view-viskhan-sbank-collaboration-1_01": HTMLCntFlexyViewViskhanSbankCollaboration1_01Element;
        "cnt-flexy-view-viskhan-sbank-dowork": HTMLCntFlexyViewViskhanSbankDoworkElement;
        "cnt-flexy-view-viskhan-sbank-dowork-1_01": HTMLCntFlexyViewViskhanSbankDowork1_01Element;
        "cnt-flexy-view-viskhan-sbank-estimates": HTMLCntFlexyViewViskhanSbankEstimatesElement;
        "cnt-flexy-view-viskhan-sbank-estimates-1_01": HTMLCntFlexyViewViskhanSbankEstimates1_01Element;
        "cnt-flexy-view-viskhan-sbank-footer": HTMLCntFlexyViewViskhanSbankFooterElement;
        "cnt-flexy-view-viskhan-sbank-footer-1_01": HTMLCntFlexyViewViskhanSbankFooter1_01Element;
        "cnt-flexy-view-viskhan-sbank-header": HTMLCntFlexyViewViskhanSbankHeaderElement;
        "cnt-flexy-view-viskhan-sbank-header-1_01": HTMLCntFlexyViewViskhanSbankHeader1_01Element;
        "cnt-flexy-view-viskhan-sbank-review": HTMLCntFlexyViewViskhanSbankReviewElement;
        "cnt-flexy-view-viskhan-sbank-review-1_01": HTMLCntFlexyViewViskhanSbankReview1_01Element;
        "cnt-flexy-view-viskhan-sbank-staffing": HTMLCntFlexyViewViskhanSbankStaffingElement;
        "cnt-flexy-view-viskhan-sbank-staffing-1_01": HTMLCntFlexyViewViskhanSbankStaffing1_01Element;
        "cnt-flexy-view-viskhan-sbank-structure": HTMLCntFlexyViewViskhanSbankStructureElement;
        "cnt-flexy-view-viskhan-sbank-structure-1_01": HTMLCntFlexyViewViskhanSbankStructure1_01Element;
        "cnt-flexy-view-viskhan-sbank-summary": HTMLCntFlexyViewViskhanSbankSummaryElement;
        "cnt-flexy-view-viskhan-sbank-summary-1_01": HTMLCntFlexyViewViskhanSbankSummary1_01Element;
        "cnt-flexy-view-viskhan-sbank-timeline": HTMLCntFlexyViewViskhanSbankTimelineElement;
        "cnt-flexy-view-viskhan-sbank-timeline-1_01": HTMLCntFlexyViewViskhanSbankTimeline1_01Element;
        "cnt-flexy-view-viskhan-window-1_01": HTMLCntFlexyViewViskhanWindow1_01Element;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CntFlexyViewViskhanSbankAbout {
        /**
          * Клик по SectionFourthButton
         */
        "onClickSectionFourthButton"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по SectionFourthImage
         */
        "onClickSectionFourthImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по SectionFourthText
         */
        "onClickSectionFourthText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по SectionFourthTitle
         */
        "onClickSectionFourthTitle"?: (event: CustomEvent<any>) => void;
        /**
          * Данные компонента Collaboration
         */
        "payload"?: any;
        /**
          * Интерфейс для SectionFourth
         */
        "sectionFourth"?: SSectionFourthItems[];
    }
    interface CntFlexyViewViskhanSbankAbout1_01 {
        "pathToAssets"?: string;
        /**
          * Данные компонента About
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankCollaboration {
        /**
          * Клик по Image
         */
        "onClickCollaborationImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtext
         */
        "onClickCollaborationSubtext"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtitle
         */
        "onClickCollaborationSubtitle"?: (event: CustomEvent<any>) => void;
        /**
          * Данные компонента collaboration
         */
        "payload"?: any;
        /**
          * Интерфейс для Collaboration
         */
        "sectionThird"?: SCollaborationItems[];
    }
    interface CntFlexyViewViskhanSbankCollaboration1_01 {
        "pathToAssets"?: string;
        /**
          * Данные компонента Collaboration
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankDowork {
        /**
          * Клик по MyBlock
         */
        "onClickDoworkMyBlock"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtitle
         */
        "onClickDoworkSubtitle"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Title
         */
        "onClickDoworkTitle"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * Массив для Dowork
         */
        "payload"?: any;
        /**
          * Интерфейс для Dowork
         */
        "sectionSecond"?: SSectionSecondItems[];
    }
    interface CntFlexyViewViskhanSbankDowork1_01 {
        "pathToAssets"?: string;
        /**
          * Данные компонента collaboration
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankEstimates {
        /**
          * Клик по Button
         */
        "onClickEstimatesButton"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Image
         */
        "onClickEstimatesImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtext
         */
        "onClickEstimatesSubtext"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Text
         */
        "onClickEstimatesText"?: (event: CustomEvent<any>) => void;
        /**
          * Массив для Estimates
         */
        "payload"?: any;
        /**
          * Интерфейс для Estimates
         */
        "sectionFirst"?: SSectionFirstItems[];
    }
    interface CntFlexyViewViskhanSbankEstimates1_01 {
        "pathToAssets"?: string;
        /**
          * Данные компонента estimates
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankFooter {
        /**
          * Массив для Footer
         */
        "categories"?: any;
        /**
          * Интерфейс для Footer
         */
        "footer"?: SFooterItems[];
        /**
          * Клик по FooterCopyright
         */
        "onClickFooterCopyright"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по FooterFacebook
         */
        "onClickFooterFacebook"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по FooterIn
         */
        "onClickFooterIn"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewViskhanSbankFooter1_01 {
        /**
          * Данные компонента footer
         */
        "categories"?: any;
        "pathToAssets"?: string;
    }
    interface CntFlexyViewViskhanSbankHeader {
        /**
          * Массив для Header
         */
        "categories"?: any;
        /**
          * Интерфейс для Header
         */
        "header"?: SHeaderItems[];
        /**
          * Клик по About
         */
        "onClickHeaderAboutUs"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Features
         */
        "onClickHeaderFeatures"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Home
         */
        "onClickHeaderHome"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по How
         */
        "onClickHeaderHowItWorks"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по лого
         */
        "onClickHeaderLogo"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по SignIn
         */
        "onClickHeaderSignIn"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewViskhanSbankHeader1_01 {
        /**
          * Данные компонента header
         */
        "categories"?: any;
        "pathToAssets"?: string;
    }
    interface CntFlexyViewViskhanSbankReview {
        /**
          * Интерфейс для SReviewItems
         */
        "Review"?: SReviewItems[];
        /**
          * Клик по Image
         */
        "onClickReviewImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtext
         */
        "onClickReviewSubtext"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtitle
         */
        "onClickReviewSubtitle"?: (event: CustomEvent<any>) => void;
        /**
          * Данные компонента Review
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankReview1_01 {
        "pathToAssets"?: string;
        /**
          * Данные компонента Review
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankStaffing {
        /**
          * Интерфейс для Staffing
         */
        "Staffing"?: SStaffingItems[];
        /**
          * Клик по Image
         */
        "onClickStaffingImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtext
         */
        "onClickStaffingSubtext"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtitle
         */
        "onClickStaffingSubtitle"?: (event: CustomEvent<any>) => void;
        /**
          * Данные компонента Staffing
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankStaffing1_01 {
        "pathToAssets"?: string;
        /**
          * Данные компонента Staffing
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankStructure {
        /**
          * Клик по Image
         */
        "onClickStructureImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtext
         */
        "onClickStructureSubtext"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtitle
         */
        "onClickStructureSubtitle"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Text
         */
        "onClickStructureText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Title
         */
        "onClickStructureTitle"?: (event: CustomEvent<any>) => void;
        /**
          * Массив для Structure
         */
        "payload"?: any;
        /**
          * Интерфейс для Structure
         */
        "sectionThird"?: SSectionThirdItems[];
    }
    interface CntFlexyViewViskhanSbankStructure1_01 {
        "pathToAssets"?: string;
        /**
          * Данные компонента collaboration
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankSummary {
        /**
          * Интерфейс для Summary
         */
        "Summary"?: SSummaryItems[];
        /**
          * Клик по Image
         */
        "onClickSummaryImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtext
         */
        "onClickSummarySubtext"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtitle
         */
        "onClickSummarySubtitle"?: (event: CustomEvent<any>) => void;
        /**
          * Данные компонента Summary
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankSummary1_01 {
        "pathToAssets"?: string;
        /**
          * Данные компонента Summary
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankTimeline {
        /**
          * Интерфейс для Timeline
         */
        "Timeline"?: STimelineItems[];
        /**
          * Клик по Image
         */
        "onClickTimelineImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtext
         */
        "onClickTimelineSubtext"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Subtitle
         */
        "onClickTimelineSubtitle"?: (event: CustomEvent<any>) => void;
        /**
          * Данные компонента Timeline
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanSbankTimeline1_01 {
        "pathToAssets"?: string;
        /**
          * Данные компонента Timeline
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanWindow1_01 {
        /**
          * Интерфейс для Window
         */
        "Window"?: SWindowItems[];
        /**
          * Клик по Circle
         */
        "onClickWindowCircle"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по EUP
         */
        "onClickWindowEUP"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по EUR
         */
        "onClickWindowEUR"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по GBP
         */
        "onClickWindowGBP"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по INR
         */
        "onClickWindowINR"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Input
         */
        "onClickWindowInput"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по JPY
         */
        "onClickWindowJPY"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по NZD
         */
        "onClickWindowNZD"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по PYG
         */
        "onClickWindowPYG"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Search
         */
        "onClickWindowSearch"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Text
         */
        "onClickWindowText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по USD
         */
        "onClickWindowUSD"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по ZAR
         */
        "onClickWindowZAR"?: (event: CustomEvent<any>) => void;
        /**
          * Закрытие модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * Данные для Window
         */
        "payload"?: any;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "cnt-flexy-view-viskhan-sbank-about": CntFlexyViewViskhanSbankAbout;
        "cnt-flexy-view-viskhan-sbank-about-1_01": CntFlexyViewViskhanSbankAbout1_01;
        "cnt-flexy-view-viskhan-sbank-collaboration": CntFlexyViewViskhanSbankCollaboration;
        "cnt-flexy-view-viskhan-sbank-collaboration-1_01": CntFlexyViewViskhanSbankCollaboration1_01;
        "cnt-flexy-view-viskhan-sbank-dowork": CntFlexyViewViskhanSbankDowork;
        "cnt-flexy-view-viskhan-sbank-dowork-1_01": CntFlexyViewViskhanSbankDowork1_01;
        "cnt-flexy-view-viskhan-sbank-estimates": CntFlexyViewViskhanSbankEstimates;
        "cnt-flexy-view-viskhan-sbank-estimates-1_01": CntFlexyViewViskhanSbankEstimates1_01;
        "cnt-flexy-view-viskhan-sbank-footer": CntFlexyViewViskhanSbankFooter;
        "cnt-flexy-view-viskhan-sbank-footer-1_01": CntFlexyViewViskhanSbankFooter1_01;
        "cnt-flexy-view-viskhan-sbank-header": CntFlexyViewViskhanSbankHeader;
        "cnt-flexy-view-viskhan-sbank-header-1_01": CntFlexyViewViskhanSbankHeader1_01;
        "cnt-flexy-view-viskhan-sbank-review": CntFlexyViewViskhanSbankReview;
        "cnt-flexy-view-viskhan-sbank-review-1_01": CntFlexyViewViskhanSbankReview1_01;
        "cnt-flexy-view-viskhan-sbank-staffing": CntFlexyViewViskhanSbankStaffing;
        "cnt-flexy-view-viskhan-sbank-staffing-1_01": CntFlexyViewViskhanSbankStaffing1_01;
        "cnt-flexy-view-viskhan-sbank-structure": CntFlexyViewViskhanSbankStructure;
        "cnt-flexy-view-viskhan-sbank-structure-1_01": CntFlexyViewViskhanSbankStructure1_01;
        "cnt-flexy-view-viskhan-sbank-summary": CntFlexyViewViskhanSbankSummary;
        "cnt-flexy-view-viskhan-sbank-summary-1_01": CntFlexyViewViskhanSbankSummary1_01;
        "cnt-flexy-view-viskhan-sbank-timeline": CntFlexyViewViskhanSbankTimeline;
        "cnt-flexy-view-viskhan-sbank-timeline-1_01": CntFlexyViewViskhanSbankTimeline1_01;
        "cnt-flexy-view-viskhan-window-1_01": CntFlexyViewViskhanWindow1_01;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cnt-flexy-view-viskhan-sbank-about": LocalJSX.CntFlexyViewViskhanSbankAbout & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankAboutElement>;
            "cnt-flexy-view-viskhan-sbank-about-1_01": LocalJSX.CntFlexyViewViskhanSbankAbout1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankAbout1_01Element>;
            "cnt-flexy-view-viskhan-sbank-collaboration": LocalJSX.CntFlexyViewViskhanSbankCollaboration & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankCollaborationElement>;
            "cnt-flexy-view-viskhan-sbank-collaboration-1_01": LocalJSX.CntFlexyViewViskhanSbankCollaboration1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankCollaboration1_01Element>;
            "cnt-flexy-view-viskhan-sbank-dowork": LocalJSX.CntFlexyViewViskhanSbankDowork & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankDoworkElement>;
            "cnt-flexy-view-viskhan-sbank-dowork-1_01": LocalJSX.CntFlexyViewViskhanSbankDowork1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankDowork1_01Element>;
            "cnt-flexy-view-viskhan-sbank-estimates": LocalJSX.CntFlexyViewViskhanSbankEstimates & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankEstimatesElement>;
            "cnt-flexy-view-viskhan-sbank-estimates-1_01": LocalJSX.CntFlexyViewViskhanSbankEstimates1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankEstimates1_01Element>;
            "cnt-flexy-view-viskhan-sbank-footer": LocalJSX.CntFlexyViewViskhanSbankFooter & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankFooterElement>;
            "cnt-flexy-view-viskhan-sbank-footer-1_01": LocalJSX.CntFlexyViewViskhanSbankFooter1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankFooter1_01Element>;
            "cnt-flexy-view-viskhan-sbank-header": LocalJSX.CntFlexyViewViskhanSbankHeader & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankHeaderElement>;
            "cnt-flexy-view-viskhan-sbank-header-1_01": LocalJSX.CntFlexyViewViskhanSbankHeader1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankHeader1_01Element>;
            "cnt-flexy-view-viskhan-sbank-review": LocalJSX.CntFlexyViewViskhanSbankReview & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankReviewElement>;
            "cnt-flexy-view-viskhan-sbank-review-1_01": LocalJSX.CntFlexyViewViskhanSbankReview1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankReview1_01Element>;
            "cnt-flexy-view-viskhan-sbank-staffing": LocalJSX.CntFlexyViewViskhanSbankStaffing & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankStaffingElement>;
            "cnt-flexy-view-viskhan-sbank-staffing-1_01": LocalJSX.CntFlexyViewViskhanSbankStaffing1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankStaffing1_01Element>;
            "cnt-flexy-view-viskhan-sbank-structure": LocalJSX.CntFlexyViewViskhanSbankStructure & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankStructureElement>;
            "cnt-flexy-view-viskhan-sbank-structure-1_01": LocalJSX.CntFlexyViewViskhanSbankStructure1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankStructure1_01Element>;
            "cnt-flexy-view-viskhan-sbank-summary": LocalJSX.CntFlexyViewViskhanSbankSummary & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankSummaryElement>;
            "cnt-flexy-view-viskhan-sbank-summary-1_01": LocalJSX.CntFlexyViewViskhanSbankSummary1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankSummary1_01Element>;
            "cnt-flexy-view-viskhan-sbank-timeline": LocalJSX.CntFlexyViewViskhanSbankTimeline & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankTimelineElement>;
            "cnt-flexy-view-viskhan-sbank-timeline-1_01": LocalJSX.CntFlexyViewViskhanSbankTimeline1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanSbankTimeline1_01Element>;
            "cnt-flexy-view-viskhan-window-1_01": LocalJSX.CntFlexyViewViskhanWindow1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanWindow1_01Element>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
